name-template: "{{RELEASE_NAME_TEMPLATE}}"
tag-template: "{{TAG_TEMPLATE}}"

categories:
  - title: "Features"
    labels:
      - enhancement
      - feature

  - title: "Bug fixes"
    labels:
      - bug
      - fix

  - title: "Documentation"
    labels:
      - documentation
      - docs

  - title: "Dependencies"
    labels:
      - dependencies

exclude-labels:
  - skip-changelog
  - chore
  - maintenance
  - ci
  - tests

change-template: "- $TITLE (#$NUMBER) @$AUTHOR <!-- moya-release:pr=$NUMBER -->"
no-changes-template: ""

version-resolver:
  major:
    labels:
      - breaking
  minor:
    labels:
      - enhancement
      - feature
  patch:
    labels:
      - bug
      - fix
      - dependencies
      - documentation
      - docs
  default: patch

template: |
  ## Release notes

  $CHANGES
